### ISSUE TITLE
Various Issues

### ISSUE THREAD

**Issue by behreajj** [Tsukina-7mochi/aseprite-type-definition#3]
Hello,

Thanks again for putting this repo together! I didn't want to flood this page with a bunch of issues, so I jotted down a few that I noticed when cleaning up my own Lua scripts.

Cheers,
Jeremy

https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/9b3f3edb910338f84efbe4c6ca1609d9b98b3aa4/definitions/aseprite.lua#L1033

returns a `Layer`.

https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/9b3f3edb910338f84efbe4c6ca1609d9b98b3aa4/definitions/aseprite.lua#L769

The `Color|integer` parameter is preceded by an `integer` for the index.

https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/9b3f3edb910338f84efbe4c6ca1609d9b98b3aa4/definitions/aseprite.lua#L1057

The frame object or number is optional.

https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/9b3f3edb910338f84efbe4c6ca1609d9b98b3aa4/definitions/aseprite.lua#L634

The final position parameter is optional.

https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/9b3f3edb910338f84efbe4c6ca1609d9b98b3aa4/definitions/aseprite.lua#L534

The shades `onclick` function accepts an event.

https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/9b3f3edb910338f84efbe4c6ca1609d9b98b3aa4/definitions/aseprite.lua#L747

The overload for the `layer:cel` method allows for either a frame or a frame number.

https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/9b3f3edb910338f84efbe4c6ca1609d9b98b3aa4/definitions/aseprite.lua#L1067

Same with `sprite:newCel`.

https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/9b3f3edb910338f84efbe4c6ca1609d9b98b3aa4/definitions/aseprite.lua#L607

An `integer` is accepted by `image:clear`.

https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/9b3f3edb910338f84efbe4c6ca1609d9b98b3aa4/definitions/aseprite.lua#L961

A `ColorSpace` can be retrieved from a `Sprite`.

https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/9b3f3edb910338f84efbe4c6ca1609d9b98b3aa4/definitions/aseprite.lua#L726

A layer's `blendMode` is `nil` if it is a group.

This is also true of a group layer's `opacity`.

https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/9b3f3edb910338f84efbe4c6ca1609d9b98b3aa4/definitions/aseprite.lua#L748

The `layer:cel` method might return either a `Cel` or `nil`.

**Comment by Tsukina-7mochi** [comment]
Thank you for pointing out the problem!
I'll fix them.
