### ISSUE TITLE
A Few Notes, Typos

### ISSUE THREAD

**Issue by behreajj** [Tsukina-7mochi/aseprite-type-definition#7]
Hi again,

This type definition continues to be very useful for me! :) I forked this repo for some more dramatic updates / customizations to fit what I needed. As part of that process I noted down typos. I thought I'd put some smaller issues here in case you were interested:

In the `BlendMode` enumeration, `HSL_COLOR` is absent at

https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/main/definitions/aseprite.lua#L229

See https://github.com/aseprite/aseprite/blob/main/src/doc/blend_mode.cpp#L32 .

For `Dialog` `combobox` widgets, one of the cases of "options?: string[]" should be "option?: string" at

https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/main/definitions/aseprite.lua#L488

An overload for `Selection` `contains` accepts integer coordinate pairs at

https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/main/definitions/aseprite.lua#L921

"ColorSpace" initial 'c' should be lowercase for the parameter name, not the type, at

https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/main/definitions/aseprite.lua#L1033

The fields for `Point`, `Rectangle` and `Size` are `integer`s, not `number`s

https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/main/definitions/aseprite.lua#L789
https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/main/definitions/aseprite.lua#L833
https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/main/definitions/aseprite.lua#L951

This can be checked in the source code at

https://github.com/aseprite/aseprite/blob/main/src/app/script/point_class.cpp#L23
https://github.com/aseprite/aseprite/blob/main/src/app/script/rectangle_class.cpp#L24
https://github.com/aseprite/aseprite/blob/main/src/app/script/size_class.cpp#L23

If I'm understanding the Lua settings in VS Code right, people wouldn't notice this change unless they set `Lua.type.castNumberToInteger` to `false`.

`putImage` is deprecated, but not `putPixel` or `putSprite` at

https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/main/definitions/aseprite.lua#L666
https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/main/definitions/aseprite.lua#L673
https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/main/definitions/aseprite.lua#L680

"numbe" should be "number" at

https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/main/definitions/aseprite.lua#L16

but also, this seems to be a `Frame` object, not a frameNumber `integer`, at least for the getter.

"filenmae" should be "filename" at

https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/main/definitions/aseprite.lua#L165

None of the comments in the enumeration are needed, in my opinion, but if kept, "shold" should be "should" at

https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/main/definitions/aseprite.lua#L293

"Braush" should be "Brush" at

https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/main/definitions/aseprite.lua#L392

"listnerCode" should be "listenerCode" at

https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/main/definitions/aseprite.lua#L574

although most return statements aren't annotated anyway.

"isntance" should be "instance" at

https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/main/definitions/aseprite.lua#L560

"spcifies" should be "specifies" at

https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/main/definitions/aseprite.lua#L982

"verstion" should be "version" at

https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/main/definitions/aseprite.lua#L1152

"comment" stub can be removed from the end of

https://github.com/Tsukina-7mochi/aseprite-type-definition/blob/main/definitions/aseprite.lua#L1169

Thanks and cheers,
Jeremy

**Comment by Tsukina-7mochi** [comment]
Thank you for pointing out! I'll fix it soon.

**Comment by Tsukina-7mochi** [comment]
> `putImage` is deprecated, but not `putPixel` or `putSprite`

I've wondering whether I should mark them deprecated because API document does not explicitly stats for them, I mean it can be an alias for `drawPixel` and `drawSprite` respectively.

**Comment by behreajj** [comment]
I see what you mean. I checked with the source code, too,

https://github.com/aseprite/aseprite/blob/main/src/app/script/image_class.cpp#L672

Both put and draw methods call the same internal methods. Only two of three of the listings are marked with `TODO`s that note a plan to deprecate them.

I guess it's up to how strict you want the definitions to be.
